# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('category', models.CharField(max_length=200)),
                ('section', models.CharField(max_length=200)),
                ('details', models.CharField(default='', max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
